"""§9 Model swap: Friday 1 from transcripts generated by two providers → identical held sets and flags."""

from __future__ import annotations

import pytest

from pakka import agent as agent_mod
from tests.conftest import fresh_state, replay


def _holds(rr):
    return sorted((w.tool, w.status, tuple((f.kind, f.reason) for f in w.flags), tuple(sorted(w.depends_on))) for w in rr.writes)


def test_two_providers_same_holds():
    tags = agent_mod.available_tags()
    if len(tags) < 2:
        pytest.skip(f"only {tags} transcripts present; generate a second set with PAKKA_MODEL set (see README §5)")
    baseline = None
    for tag in tags:
        rr = replay(fresh_state(), 1, tag=tag)
        holds = _holds(rr)
        if baseline is None:
            baseline = holds
        else:
            assert holds == baseline, tag


def test_replay_is_identical_every_time():
    a = replay(fresh_state(), 1)
    b = replay(fresh_state(), 1)
    assert a.model_dump() == b.model_dump()
